language: node_js
node_js: '12'

os:
  - linux

branches:
  only:
    - 'master'
    - 'next'

script:
  - npm run lint
  - npm run test:unit
  - '[[ ! -z "$SAUCE_ACCESS_KEY" ]] && travis_wait npm run test:visual || true'

after_success:
  # Upload screenshots to Argos
  - '[[ ! -z "$ARGOS_TOKEN" ]] && argos upload test/screenshots/local -C $TRAVIS_COMMIT -B $TRAVIS_BRANCH -T $ARGOS_TOKEN || true'

before_deploy:
  - npm run build
  - npm run docs

deploy:
  - provider: script
    script: npx semantic-release
    on:
      branch: master

  - provider: pages
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./docs
    on:
      branch: master
