language: node_js
node_js: '10'

os:
  - linux

script:
  - npm run build
  # The `--no-cache` flag disables ParcelJS's cache as it can cause errors with building
  # same entries targetting different destinations.
  - npm run pages -- --no-cache
  - npm run pages:test -- --no-cache
  - travis_wait npm run test -- --no-cache

after_success:
  - argos upload test/screenshots/local -C $TRAVIS_COMMIT -B $TRAVIS_BRANCH -T $ARGOS_TOKEN || true

deploy:
  # Do a semantic release
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master

  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep_history: true
    local-dir: ./pages
    on:
      branch: master
